global:
  load1-ip-port: eureka1:9991
  load2-ip-port: eureka2:9992
  load3-ip-port: eureka3:9993
server:
  name: feign
  port: 9903
spring:
  application:
    name: feign
  zipkin:
    base-url: http://127.0.0.1:9411/  # zipkin服务器的地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: web  # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%
eureka:
  client:
    service-url:
      defaultZone: http://${global.load1-ip-port}/eureka/,http://${global.load2-ip-port}/eureka/,http://${global.load3-ip-port}/eureka/
# 开启熔断
feign:
  hystrix:
    enabled: true